version: '3'

services:
  web:
    build: .
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - .:/var/www
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: iacarvalho
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
 
volumes:
  dbdata:
